# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='profile/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.FileField(upload_to='profile/%Y/%m/%d'),
        ),
    ]
