# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161013_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='image',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
