# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161013_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Media',
        ),
    ]
