# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_media_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='document',
            new_name='media',
        ),
    ]
