# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20161013_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(upload_to='media/'),
        ),
    ]
